### ISSUE TITLE
Producteur des ressources

### ISSUE THREAD

**Issue by pachevalier** [SocialGouv/ressourcerie#56]
Le producteur du guide "Pseudonymiser des documents grâce à l'IA" n'est pas le MTEI mais le Lab IA de la DINUM, au même titre que api.gouv.fr

Même remarque pour l'inventaire des modèles du Lab IA : https://ressourcerie.fabrique.social.gouv.fr/les-api/modeles_apprentissage

**Comment by YoannNumericite** [comment]
Merci pour ces précisions, c'est corrigé.
